name: .Net5 CI

on:
  workflow_dispatch:
  push:
    branches: [ master, develop ]
    paths:
      - 'src/**'
      - '!src/WebUI/ClientApp/**'
      - '!**.md'
  pull_request:
    branches: [ master, develop ]
    paths:
      - 'src/**'

env:
  project: './src/WebUI/WebUI.csproj'

jobs:
  Restore_Build_Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 5
        uses: actions/setup-dotnet@v3.0.2
        with:
          dotnet-version: 5.0.301

      - name: Use latest Node.js version
        uses: actions/setup-node@master

      - name: Install dependencies
        run: dotnet restore ${{ env.project }}

      - name: Build with dotnet
        run: dotnet build ${{ env.project }} --configuration Release --no-restore

      - name: Run Test
        run: dotnet test ${{ env.project }} --no-restore --verbosity normal
